name: CI

# Trigger the workflow on push or pull request
on: [ push, pull_request ]

jobs:

  build-and-test-macos:
    strategy:
      matrix:
        os: [ macos-13 ]
        timeout_override: [ true ]
        brew_install_flags: [ '--force -v' ]
      fail-fast: false
    name: "Build/Test: ${{ matrix.os }}"
    uses: ./.github/workflows/build-and-test-macos.yml
    with:
      os: ${{ matrix.os }}
      ghc_version: 9.6.7
      hls_version: 2.10.0.0
      timeout_override: ${{ matrix.timeout_override }}
      brew_install_flags: ${{ matrix.brew_install_flags }}
    secrets: inherit

