name: CI

# Trigger the workflow on push or pull request
on: [ push, pull_request ]

jobs:

  # ------------------------------
  # Test the building of documentation

  build-doc-macOS:
    name: "Build doc"
    runs-on: macos-14
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        shell: bash
        run: |
          brew install texlive
          #tail -100 /var/log/install.log
