name: CI

# Trigger the workflow on push or pull request
on: [ push, pull_request ]

jobs:

  # ------------------------------
  # Test the building of documentation

  build-doc-macOS:
    strategy:
      matrix:
        os: [ macos-14 ]
      fail-fast: false
    name: "Build doc: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        shell: bash
        run: |
          brew update
          brew install -v mactex-no-gui
